name: run app test 

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  widget_test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2

      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git

      # PATH を通す
      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      # パッケージのダウンロード
      - name: Download Flutter packages
        run: flutter pub get

      - name: flutter test
        run: flutter test 